<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\UseCases\" />
    <Folder Include="Interfaces\Data\" />
    <Folder Include="Interfaces\" />
    <Folder Include="UseCases\" />
  </ItemGroup>

</Project>
